version: 2.1
jobs:
  build:
    working_directory: ~/codezest
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command: yarn install
      - run:
        name: Production Build
        command: yarn build
